### ISSUE TITLE
Democontent for PageKit

### ISSUE THREAD

**Issue by AnNemo** [nick2ld/verti-theme#1]
Hi there, 
is it possiblie to install some democontent in pagekit (Theme Verti)?

**Comment by nick2ld** [comment]
Hey. Unfortunately - no. I can only just do a dump - an example ... if it is very necessary, and ask questions - can answer or explain ...

**Comment by AnNemo** [comment]
Can u send me a DB Dump? So i can import your democontent. 
I don't finf out, how u create the content in pagekit

**Comment by nick2ld** [comment]
[create the content in pagekit](https://pagekit.com/docs/user-interface/site)
or [The Blog extension](https://pagekit.com/docs/user-interface/blog)
